- name: Inits kubernetes cluster
  args:
    chdir: /root
    creates: /root/init-output
  delegate_to: "{{ k8s_init_node | default(groups['masters'][0]) }}"
  register: kube_initialized
  run_once: True
  shell: "kubeadm init --{{ init_args | join(' --') }} >init-output 2>&1"
  vars:
    init_args:
    - "token-ttl={{ k8s_init_token_ttl }}"
    - upload-certs
    - ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml
- name: Syncs init output accross nodes
  delegate_to: "{{ k8s_init_node | default(groups['masters'][0]) }}"
  synchronize:
    dest: /root/k8s-init
    src: /root/init-output
- name: Syncs admin config accross nodes
  delegate_to: "{{ k8s_init_node | default(groups['masters'][0]) }}"
  synchronize:
    dest: /root/.kube/config
    src: /etc/kubernetes/admin.conf
