- name: init kubernetes cluster
  delegate_to: '{{ k8s_init_node }}'
  register: kube_initialized
  run_once: True
  shell: kubeadm init --token-ttl=0 >init-output 2>&1 chdir=/root creates=/root/init-output
- name: sync init output accross nodes
  delegate_to: '{{ k8s_init_node }}'
  synchronize: dest=/root/k8s-init src=/root/init-output
- name: sync admin config accross nodes
  delegate_to: '{{ k8s_init_node }}'
  synchronize: dest=/root/.kube/config src=/etc/kubernetes/admin.conf
- name: get k8s version
  changed_when: False
  delegate_to: '{{ k8s_init_node }}'
  register: k8s_version
  run_once: True
  shell: kubectl version | base64 | tr -d '\n' creates=/ur/src/weave.yml
- name: download weave network driver
  delegate_to: '{{ k8s_init_node }}'
  run_once: True
  register: weave_fetched
  get_url: "url='https://cloud.weave.works/k8s/net?k8s-version={{ k8s_version.stdout }}&env.IPALLOC_RANGE={{ k8s_overlay_cidr | default('10.32.0.0/12') }}' dest=/usr/src/weave.yml owner=root group=root mode=0644"
- name: install weave network driver
  delegate_to: '{{ k8s_init_node }}'
  run_once: True
  shell: kubectl apply -f weave.yml chdir=/usr/src
  when: weave_fetched is defined and weave_fetched.changed is defined and weave_fetched.changed == True
- name: get join command
  changed_when: False
  register: k8s_join_command
  shell: grep 'kubeadm join' k8s-init chdir=/root
- name: join cluster
  shell: "{{ k8s_join_command.stdout | default('') }} >init-output 2>&1 chdir=/root creates=/root/init-output"
  when: k8s_join_command is defined and k8s_join_command.stdout is defined and k8s_join_command != ""
