- name: install k8s apt key
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - creates=/etc/apt/sources.list.d/k8s.list warn=False
- name: install k8s sources list
  register: update_cache
  template: src=sources.j2 dest=/etc/apt/sources.list.d/k8s.list owner=root group=root mode=0644
- name: update apt cache
  apt: update_cache=yes
  delay: 10
  retries: 2
  when: update_cache is defined and update_cache.changed == True
- name: install kube configuration directory
  file: dest=/root/.kube state=directory owner=root group=root mode=0750
- name: install kubectl
  apt: name=kubeadm state=present
