- name: check dphys-swapfile status
  changed_when: False
  failed_when: False
  shell: test -s dphys-swapfile chdir=/etc
  register: dphys_stat
- name: stop dphys-swapfile service
  shell: dphys-swapfile swapoff
  when: dphys_stat.rc is defined and dphys_stat.rc == 0
- name: stop dphys-swapfile service
  shell: dphys-swapfile uninstall
  when: dphys_stat.rc is defined and dphys_stat.rc == 0
- name: stop dphys-swapfile service
  shell: update-rc.d dphys-swapfile remove
  when: dphys_stat.rc is defined and dphys_stat.rc == 0
- name: drop dphys-swapfile configuration
  shell: rm -f dphys-swapfile chdir=/etc
  when: dphys_stat.rc is defined and dphys_stat.rc == 0
