- name: Checks dphys-swapfile status
  args:
    chdir: /etc
  changed_when: False
  failed_when: False
  shell: test -s dphys-swapfile
  register: dphys_stat
- block:
  - name: Stops dphys-swapfile service
    shell: dphys-swapfile swapoff
  - name: Stops dphys-swapfile service
    shell: dphys-swapfile uninstall
  - name: Stops dphys-swapfile service
    shell: update-rc.d dphys-swapfile remove
  - name: Drops dphys-swapfile configuration
    args:
      chdir: /etc
    shell: rm -f dphys-swapfile
  when:
  - dphys_stat.rc is defined
  - dphys_stat.rc == 0
