- name: get local host key
  changed_when: False
  register: ssh_public_key
  shell: cat id_rsa.pub chdir=/root/.ssh
- name: exchange ssh keys between k8s nodes
  authorized_key: user={{ ansible_user | default('root') }} key={{ item[0] }}
  delegate_to: "{{ item[1] }}"
  with_nested:
    - "{{ ssh_public_key.stdout }}"
    - "{{ groups['k8s'] }}"
