- name: Gets local host key
  args:
    chdir: /root/.ssh
  changed_when: False
  register: ssh_public_key
  shell: cat id_rsa.pub
- name: Exchanges ssh keys between k8s nodes
  authorized_key:
    key: "{{ item[0] }}"
    user: "{{ ansible_user | default('root') }}"
  delegate_to: "{{ item[1] }}"
  with_nested:
  - "{{ ssh_public_key.stdout }}"
  - "{{ groups['k8s'] }}"
