- name: Ensures .ssh directory exists
  file:
    dest: /root/.ssh
    group: root
    mode: 0700
    owner: root
    state: directory
- name: Generates ssh keys
  args:
    chdir: /root/.ssh
    creates: /root/.ssh/id_rsa
  shell: ssh-keygen -t rsa -b 4096 -N '' -f id_rsa
- name: Makes sure we have a known hosts file
  args:
    chdir: /root/.ssh
    creates: /root/.ssh/known_hosts
  shell: touch known_hosts
