- name: check for kernel modules availability
  changed_when: False
  failed_when: False
  register: kernel_availability
  shell: "test -d {{ ansible_kernel }} -o -L {{ ansible_kernel }} chdir=/lib/modules"
- name: get last kernel module available
  register: last_version
  shell: ls -1 | tail -1 chdir=/lib/modules
  when: kernel_availability is defined and kernel_availability.rc is defined and kernel_availability.rc != 0
- name: link most recent kernel module
  file: src=/lib/modules/{{ last_version.stdout }} dest=/lib/modules/{{ ansible_kernel }} state=link
  when: last_version is defined and last_version.stdout is defined and last_version.stdout != ""
