- name: Installs ntpdate
  apt:
    name: ntpdate
    state: present
  register: ntp_init
- name: Ensures we'ld sync with upstream, even if skew too large for ntpd
  shell: "ntpdate {{ ntpd_upstream_server | default('pool.ntp.org') }}"
  when:
  - ntp_init is defined
  - ntp_init is changed
- name: Installs ntpd
  apt:
    name: ntp
    state: present
- name: Configures ntpd upstream
  notify: Reload ntpd
  template:
    dest: /etc/ntp.conf
    group: root
    mode: 0644
    owner: root
    src: ntp.j2
- meta: flush_handlers
- name: Ensures ntpd would start on boot
  service:
    enabled: yes
    name: ntp
    state: started
