- name: install docker
  args:
    creates: /usr/bin/docker
    warn: False
  shell: curl -sSL get.docker.com | sh
- name: ensure docker installed
  apt:
    name:
    - containerd.io
    - docker-ce
    - docker-ce-cli
    state: present
