- name: Checks for existing namespace
  changed_when: False
  failed_when: False
  register: has_ns
  shell: "kubectl describe ns {{ traefik_namespace }}"
- name: Creates traefik namespace
  shell: "kubectl create ns {{ traefik_namespace }}"
  when:
  - has_ns is defined
  - (has_ns.rc | default(0)) != 0
- name: Checks for existing secret
  changed_when: False
  failed_when: False
  register: has_secret
  shell: "kubectl describe secret -n {{ traefik_namespace }} traefik"
